### ISSUE TITLE
Applying letter scheme to sessions

### ISSUE THREAD

**Issue by tobipch** [Lykos/cube_trainer#1403]
**Is your feature request related to a problem? Please describe.**
When I'm practicing 2-Twists (with image), then my defined letter scheme does not get applied. The letters in the table below are wrong. This obviously also applies to the letter-mode.

**Describe the solution you'd like**
My letter scheme should be applied.

**Comment by Lykos** [comment]
Thanks for reporting, will try to fix it next weekend.
